### PR TITLE
Responsiveness

### PR DESCRIPTION
**Pull request by Developers-codz**
Added responsiveness, absolute path, and created drawer for a smaller screen, click on the logo on the navbar to open and close drawer

### CODE REVIEW

**Review by Dev-AkshatGupta — APPROVED** [review]
Nice  code Kajal I loved it 
You can go ahead and merge it nothing to suggest very small pr

**Review by Kavita539 — APPROVED** [review]
- code looks neat and clean
- UI looks great, loved the color theme
- Great work on responsiveness
- Overall looks good and can be merged

**Comment by Developers-codz** [comment]
> Nice code Kajal I loved it You can go ahead and merge it nothing to suggest very small pr

thank you Akshat

**Comment by Developers-codz** [comment]
> * code looks neat and clean
> * UI looks great, loved the color theme
> * Great work on responsiveness
> * Overall looks good and can be merged

Thank you Kavita

**Pull request merged**
